export * from './emitter'
export * from './getPage'
export * from './isIOS'
export * from './isPC'
export * from './isSkyline'
export * from './sleep'
export * from './wxErrTip'
export * from './wxToPromise'
